"""empty message

Revision ID: 06f6466ebf0a
Revises: 6da4fa316fa6
Create Date: 2020-03-03 09:58:42.470724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f6466ebf0a'
down_revision = '6da4fa316fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_5_delete_hash')
    op.drop_column('products', 'image_5_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_5_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('image_5_delete_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
