"""empty message

Revision ID: 14679ae353c4
Revises: d57e34b9fa8d
Create Date: 2020-02-18 16:47:08.875634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14679ae353c4'
down_revision = 'd57e34b9fa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
