"""empty message

Revision ID: 36318553a962
Revises: 8953f0347bde
Create Date: 2019-12-27 10:25:55.095036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36318553a962'
down_revision = '8953f0347bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'created_by')
    # ### end Alembic commands ###
