"""empty message

Revision ID: 412ed32a5c7a
Revises: da6507a0ab59
Create Date: 2020-02-09 17:12:34.224050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412ed32a5c7a'
down_revision = 'da6507a0ab59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Integer(), nullable=True))
    op.drop_column('users', 'shop_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shop_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
