"""empty message

Revision ID: 65bb6ea20db7
Revises: 70c3add4217d
Create Date: 2019-12-27 09:02:40.633329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65bb6ea20db7'
down_revision = '70c3add4217d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
