"""empty message

Revision ID: 77ceab75c8bd
Revises: cc617b0ae942
Create Date: 2019-12-27 09:01:15.850348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ceab75c8bd'
down_revision = 'cc617b0ae942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
