"""empty message

Revision ID: 7ad2e93ef375
Revises: 89f323f2b476
Create Date: 2020-02-09 20:54:45.299473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad2e93ef375'
down_revision = '89f323f2b476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('email', sa.String(length=50), nullable=True))
    op.drop_column('shops', 'email_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('email_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('shops', 'email')
    # ### end Alembic commands ###
