"""empty message

Revision ID: 95b0082d619f
Revises: 412ed32a5c7a
Create Date: 2020-02-09 20:27:41.507270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b0082d619f'
down_revision = '412ed32a5c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('owns_shop', sa.Integer(), nullable=True))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'owns_shop')
    # ### end Alembic commands ###
