"""empty message

Revision ID: 976bc834412f
Revises: 16cf971decde
Create Date: 2020-02-18 08:04:06.868585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976bc834412f'
down_revision = '16cf971decde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('detail_1', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('detail_2', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('detail_3', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('detail_4', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('detail_5', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_1_delete_hash', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_1_url', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_2_delete_hash', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_2_url', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_3_delete_hash', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_3_url', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_4_delete_hash', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_4_url', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_5_delete_hash', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_5_url', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'shops', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'shop_id')
    op.drop_column('products', 'image_5_url')
    op.drop_column('products', 'image_5_delete_hash')
    op.drop_column('products', 'image_4_url')
    op.drop_column('products', 'image_4_delete_hash')
    op.drop_column('products', 'image_3_url')
    op.drop_column('products', 'image_3_delete_hash')
    op.drop_column('products', 'image_2_url')
    op.drop_column('products', 'image_2_delete_hash')
    op.drop_column('products', 'image_1_url')
    op.drop_column('products', 'image_1_delete_hash')
    op.drop_column('products', 'detail_5')
    op.drop_column('products', 'detail_4')
    op.drop_column('products', 'detail_3')
    op.drop_column('products', 'detail_2')
    op.drop_column('products', 'detail_1')
    # ### end Alembic commands ###
