"""empty message

Revision ID: bc78c0173b24
Revises: f9d4ac11e615
Create Date: 2019-12-18 08:29:11.527992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc78c0173b24'
down_revision = 'f9d4ac11e615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('measurements', sa.String(length=255), nullable=True))
    op.drop_column('products', 'dimensions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('dimensions', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('products', 'measurements')
    # ### end Alembic commands ###
