"""empty message

Revision ID: c74e4690443f
Revises: 2d001b4633e2
Create Date: 2019-12-17 09:33:08.248705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74e4690443f'
down_revision = '2d001b4633e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
