"""empty message

Revision ID: e4d7f0588e47
Revises: 9d5e05285857
Create Date: 2019-12-27 08:13:45.957035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d7f0588e47'
down_revision = '9d5e05285857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shop_name', sa.String(length=255), nullable=True))
    op.drop_column('users', 'shop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shop', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'shop_name')
    # ### end Alembic commands ###
