"""empty message

Revision ID: ebb10b85761b
Revises: 36318553a962
Create Date: 2019-12-27 13:45:34.684219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb10b85761b'
down_revision = '36318553a962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'created_by')
    # ### end Alembic commands ###
