"""empty message

Revision ID: ef15bdfdcf12
Revises: fdde9c632bc2
Create Date: 2019-12-15 22:32:06.222826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef15bdfdcf12'
down_revision = 'fdde9c632bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon_url', sa.String(length=255), nullable=True))
    op.drop_column('categories', 'icon_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('categories', 'icon_url')
    # ### end Alembic commands ###
